name: 💀💀💀

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o kaching main.go

      # - name: Test
      #   run: go test -v ./...

      - uses: actions/upload-artifact@v3
        with:
          name: binary-artifact
          path: ./kaching
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: binary-artifact

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: scp binary to server and apply latest version
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -r kaching ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_SERVER }}:${{ secrets.KACHING_PATH }}/kaching.new
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_SERVER }} << 'ENDSSH'
            echo "** restarting service tof apply new version **"
            sudo service kaching stop
            echo "** service stopped **"
            mv ${{ secrets.KACHING_PATH }}/kaching.new ${{ secrets.KACHING_PATH }}/kaching
            chmod +x ${{ secrets.KACHING_PATH }}/kaching
            sudo service kaching start
            echo "** service started **"
            ps -ef | grep kaching
          ENDSSH
